variables:
    PROJ_WEBAPI_LOC: '.\eBauGISTriage\BUDSharedWebApiCore'
#Stages  
stages:
  - build
  - publish

#Jobs
create_WebApi_nuget:
  stage: build
  #only:
  #  - tags  # the build process will only be started by git tag commits
  script: |
    cd "$env:PROJ_WEBAPI_LOC"
    & "$env:DOTNET_PATH" restore
    $versionStr = "$env:CI_COMMIT_TAG.$env:CI_PIPELINE_IID"
    Write-Host "Version: $versionStr" -ForegroundColor DarkGreen
    mkdir "$env:NUGETOUTPUT"
    & "$env:DOTNET_PATH" pack BUDSharedWebApiCore.csproj --output "$env:NUGETOUTPUT" --configuration=Debug -p:SymbolPackageFormat=snupkg --include-symbols --include-source -p:PackageVersion=$env:CI_COMMIT_TAG -p:AssemblyVersion=$versionStr -p:FileVersion=$versionStr
  artifacts:
    paths:
      - $env:PROJ_WEBAPI_LOC\$env:NUGETOUTPUT\*.nupkg
      - $env:PROJ_WEBAPI_LOC\$env:NUGETOUTPUT\*.snupkg
    expire_in: 2 days

publish_WebApi_nuget:
  stage: publish
  only:
    - tags  # the build process will only be started by git tag commits
  script: |
    $path = Join-Path -Path "$env:PROJ_WEBAPI_LOC" -ChildPath "$env:NUGETOUTPUT"
    cd "$path"
    & "$env:DOTNET_PATH" nuget push *.nupkg --source $env:BAGETSERVER --api-key $env:BAGETAPIKEY

