// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BUDSharedCore.Persistence.Model.Entities
{
    [Table("GEMEINDEN_BL")]
    public partial class GemeindenBL
    {
        [Key]
        [Column("GEM_ID", TypeName = "NUMBER(8)")]
        public int Id { get; set; }
        [Column("CODE", TypeName = "NUMBER(8)")]
        public int? Code { get; set; }
        [Column("BFS_NR", TypeName = "NUMBER(8)")]
        public int? BFSNr { get; set; }
        [Column("PLZ")]
        [StringLength(10)]
        public string Plz { get; set; }
        [Column("GEM_NAME")]
        [StringLength(100)]
        public string Name { get; set; }
        [Column("BEZIRK")]
        [StringLength(100)]
        public string Bezirk { get; set; }
        [Column("KANTON")]
        [StringLength(2)]
        public string Kanton { get; set; }
        [Column("LAND")]
        [StringLength(4)]
        public string Land { get; set; }
        [Column("X", TypeName = "NUMBER(8,2)")]
        public float? X { get; set; }
        [Column("Y", TypeName = "NUMBER(8,2)")]
        public float? Y { get; set; }
        [Column("X_LV95", TypeName = "NUMBER(9,2)")]
        public float? Xlv95 { get; set; }
        [Column("Y_LV95", TypeName = "NUMBER(9,2)")]
        public float? Ylv95 { get; set; }
    }
}