// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BUDSharedCore.Persistence.Model.Entities
{
    [Table("MA")]
    public partial class Mitarbeiter
    {
        [Key]
        [Column("ID", TypeName = "NUMBER(8)")]
        public int Id { get; set; }

        [Column("VORNAME")]
        [StringLength(255)]
        public string Vorname { get; set; }

        [Column("NACHNAME")]
        [StringLength(255)]
        public string Nachname { get; set; }

        [Column("POSITION")]
        [StringLength(255)]
        public string Position { get; set; }

        [Column("FIRMA")]
        [StringLength(255)]
        public string Firma { get; set; }

        [Column("ABTEILUNG")]
        [StringLength(255)]
        public string Abteilung { get; set; }

        [Column("BÜRO")]
        [StringLength(255)]
        public string Buero { get; set; }

        [Column("POSTFACH")]
        [StringLength(255)]
        public string Postfach { get; set; }

        [Column("STRAßE")]
        [StringLength(255)]
        public string Strasse { get; set; }

        [Column("ORT")]
        [StringLength(255)]
        public string Ort { get; set; }

        [Column("PLZ")]
        [StringLength(255)]
        public string PLZ { get; set; }

        [Column("TELEFON")]
        [StringLength(255)]
        public string TelefonNr { get; set; }

        [Column("MOBILTELEFON")]
        [StringLength(255)]
        public string MobiltelefonNr { get; set; }

        [Column("PAGER")]
        [StringLength(255)]
        public string Pager { get; set; }

        [Column("ALIAS")]
        [StringLength(255)]
        public string ADUsername { get; set; }

        [Column("INFORMATIKER", TypeName = "NUMBER(1)")]
        public bool? IsInformatiker { get; set; }

        [Column("HELPDESK", TypeName = "NUMBER(1)")]
        public bool? IsHelpdesk { get; set; }

        [Column("DST_ID", TypeName = "NUMBER(8)")]
        public int? DstId { get; set; }

        [Column("PROT_LEVEL", TypeName = "NUMBER(1)")]
        public bool? ProtLevel { get; set; }

        [Column("AKTIV", TypeName = "NUMBER(1)")]
        public bool? IsAktiv { get; set; }

        [Column("MAIL")]
        [StringLength(100)]
        public string Email { get; set; }

        [Column("WIN7", TypeName = "NUMBER(1)")]
        public bool? Win7 { get; set; }

        [Column("HOSTNAME")]
        [StringLength(255)]
        public string Hostname { get; set; }

        [Column("IP")]
        [StringLength(255)]
        public string IP { get; set; }

        [Column("LETZTER_LOGON", TypeName = "DATE")]
        public DateTime? LetzterLogon { get; set; }

        [Column("ERFASSUNGSDATUM", TypeName = "DATE")]
        public DateTime? ErfassungsDatum { get; set; }

        [Column("DEAKTIVIERDATUM", TypeName = "DATE")]
        public DateTime? DeaktivierDatum { get; set; }

        [Column("LOGON")]
        [StringLength(255)]
        public string Logon { get; set; }

        [Column("ABLAUF_PW", TypeName = "DATE")]
        public DateTime? AblaufPW { get; set; }

        [Column("FUNKTION")]
        [StringLength(255)]
        public string Funktion { get; set; }

        [Column("MOBILE_VPN")]
        [StringLength(50)]
        public string MobileVPN { get; set; }

        [ForeignKey(nameof(DstId))]
        [InverseProperty("Mitarbeiter")]
        public virtual Amt Dienststelle { get; set; }

        [NotMapped]
        public string DisplayName
        {
            get
            {
                string result =  !string.IsNullOrWhiteSpace(Nachname) ?
                    !string.IsNullOrWhiteSpace(Vorname) ? string.Format("{0} {1}", Vorname, Nachname) : Nachname
                    : ADUsername;

                if(Dienststelle != null)
                {
                    result = $"{result} ({Dienststelle.Kuerzel})";
                }

                return result;
            }
        }
    }
}
