// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BUDSharedCore.Persistence.Model.Entities
{
    [Table("V_MA_ORGANISATION")]
    public partial class VMaOrganisation
    {
        [Column("ID", TypeName = "NUMBER(8)")]
        public int Id { get; set; }

        [Column("VORNAME")]
        [StringLength(255)]
        public string Vorname { get; set; }

        [Column("NACHNAME")]
        [StringLength(255)]
        public string Nachname { get; set; }

        [Column("POSITION")]
        [StringLength(255)]
        public string Position { get; set; }

        [Column("FIRMA")]
        [StringLength(255)]
        public string Firma { get; set; }

        [Column("ABTEILUNG")]
        [StringLength(255)]
        public string Abteilung { get; set; }

        [Column("ZIMMER")]
        [StringLength(255)]
        public string Buero { get; set; }

        [Column("POSTFACH")]
        [StringLength(255)]
        public string Postfach { get; set; }

        [Column("STRASSE")]
        [StringLength(255)]
        public string Strasse { get; set; }

        [Column("ORT")]
        [StringLength(255)]
        public string Ort { get; set; }

        [Column("PLZ")]
        [StringLength(255)]
        public string PLZ { get; set; }

        [Column("TELEFON")]
        [StringLength(255)]
        public string TelefonNr { get; set; }

        [Column("MOBILTELEFON")]
        [StringLength(255)]
        public string MobiltelefonNr { get; set; }

        [Column("PAGER")]
        [StringLength(255)]
        public string Pager { get; set; }

        [Column("ALIAS")]
        [StringLength(255)]
        public string ADUsername { get; set; }

        [Column("DST_ID", TypeName = "NUMBER(8)")]
        public int? DstId { get; set; }

        [Column("AKTIV", TypeName = "NUMBER(1)")]
        public bool? IsAktiv { get; set; }

        [Column("MAIL")]
        [StringLength(100)]
        public string Email { get; set; }
        
        [Column("GRUPPENID", TypeName = "NUMBER(8)")]
        public int GruppenId { get; set; }
        
        [Column("KUERZEL")]
        [StringLength(4)]
        public string GruppenKuerzel { get; set; }
        
        [Column("BEZEICHUNG")]
        [StringLength(50)]
        public string Gruppe { get; set; }

        [NotMapped]
        public string DisplayName
        {
            get
            {
                return !string.IsNullOrWhiteSpace(Nachname) ?
                    !string.IsNullOrWhiteSpace(Vorname) ? string.Format("{0} {1}", Vorname, Nachname) : Nachname
                    : ADUsername;
            }
        }
    }
}
