DROP USER BUD_USER CASCADE;

CREATE USER BUD_USER
  IDENTIFIED BY <password>
  HTTP DIGEST DISABLE
  DEFAULT TABLESPACE BUD
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 2 Roles for BUD_USER 
GRANT BUD_SEC_READ TO BUD_USER;
GRANT CONNECT TO BUD_USER;
ALTER USER BUD_USER DEFAULT ROLE ALL;

-- 1 Tablespace Quota for BUD_USER 
ALTER USER BUD_USER QUOTA UNLIMITED ON BUD;

---------------------------------------------------------------------------------------------------------
-- Roles
--
-- run this a system user!!! only if they don't exists
--

CREATE ROLE BUD_READ NOT IDENTIFIED;
CREATE ROLE BUD_WORK NOT IDENTIFIED;

---------------------------------------------------------------------------------------------------------
-- BUD_READ  (Role) 
--
-- run this BUD!!!
--
-- data tables
--
                      
GRANT SELECT ON BUD.MA TO BUD_READ;
GRANT SELECT ON BUD.AMT TO BUD_READ;
GRANT SELECT ON BUD.BGV_GEB TO BUD_READ;
GRANT SELECT ON BUD.BGV_PERSON TO BUD_READ;
GRANT SELECT ON BUD.GEBAEUDE_EGID TO BUD_READ;
GRANT SELECT ON BUD.GEMEINDE TO BUD_READ;
GRANT SELECT ON BUD.GEMEINDE_BBOX TO BUD_READ;
GRANT SELECT ON BUD.GEMEINDE_CODE_KREIS_TBA TO BUD_READ;
GRANT SELECT ON BUD.GEMEINDEN_BL TO BUD_READ;
GRANT SELECT ON BUD.HAUSNUMMERN_BL TO BUD_READ;                


-- BUD_SEC views
--   

---------------------------------------------------------------------------------------------------------
-- BUD_WORK              (Role) 
--
-- CREATE ROLE BUD_WORK             NOT IDENTIFIED;

-- data tables
--
GRANT SELECT, INSERT, UPDATE, DELETE ON BUD.MA TO BUD_WORK; 
GRANT SELECT, INSERT, UPDATE, DELETE ON BUD.AMT TO BUD_WORK;
GRANT SELECT, INSERT, UPDATE, DELETE ON BUD.BGV_GEB TO BUD_WORK;
GRANT SELECT, INSERT, UPDATE, DELETE ON BUD.BGV_PERSON TO BUD_WORK;
GRANT SELECT, INSERT, UPDATE, DELETE ON BUD.GEBAEUDE_EGID TO BUD_WORK;
GRANT SELECT, INSERT, UPDATE, DELETE ON BUD.GEMEINDE TO BUD_WORK;
GRANT SELECT, INSERT, UPDATE, DELETE ON BUD.GEMEINDE_BBOX TO BUD_WORK;
GRANT SELECT, INSERT, UPDATE, DELETE ON BUD.GEMEINDE_CODE_KREIS_TBA TO BUD_WORK;
GRANT SELECT, INSERT, UPDATE, DELETE ON BUD.GEMEINDEN_BL TO BUD_WORK;
GRANT SELECT, INSERT, UPDATE, DELETE ON BUD.HAUSNUMMERN_BL TO BUD_WORK;


GRANT BUD_READ TO BUD_USER;